# Generated by Django 3.1.3 on 2021-02-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudPractice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
